from __future__ import annotations

import hashlib
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .packet import PACKET_BUDGET_ESTIMATOR, estimate_packet_tokens
from .store import MemoryStore


@dataclass(frozen=True)
class SummarySpec:
    name: str
    title: str
    domains: tuple[str, ...] = ()
    exclude_domains: tuple[str, ...] = ()
    token_budget: int = 2400


class SummaryProjector:
    """Deterministic current-memory projection regenerated only from SQLite."""

    def __init__(self, store: MemoryStore):
        self.store = store

    def render(self, spec: SummarySpec) -> str:
        if spec.token_budget < 96:
            raise ValueError("token_budget must be at least 96")
        rows = self.store.current_view()
        if spec.domains:
            rows = [row for row in rows if row["domain"] in spec.domains]
        if spec.exclude_domains:
            rows = [
                row for row in rows
                if row["domain"] not in spec.exclude_domains
            ]
        rows.sort(key=lambda row: (row["domain"], row["record_id"]))
        prefix = [
            f"# {spec.title}",
            "",
            "> GENERATED PROJECTION. Agent Memory Core SQLite is canonical.",
            "> Do not edit this file as a second source of truth.",
            f"> Budget: {spec.token_budget} ({PACKET_BUDGET_ESTIMATOR})",
            "",
        ]
        mandatory = self._join(prefix)
        if estimate_packet_tokens(mandatory) > spec.token_budget:
            raise ValueError("token_budget is too small for summary framing")
        selected: list[dict[str, Any]] = []
        for row in rows:
            candidate = self._join(prefix + self._body(selected + [row]))
            if estimate_packet_tokens(candidate) <= spec.token_budget:
                selected.append(row)
        output = self._join(prefix + self._body(selected))
        if estimate_packet_tokens(output) > spec.token_budget:
            raise RuntimeError("summary projection violated its hard budget")
        return output

    @staticmethod
    def _body(rows: list[dict[str, Any]]) -> list[str]:
        lines: list[str] = []
        current_domain = None
        for row in rows:
            if row["domain"] != current_domain:
                current_domain = row["domain"]
                lines.extend(
                    [f"## {current_domain.replace('_', ' ').title()}", ""]
                )
            lines.extend(
                [
                    f"### {row['title']}",
                    row["summary"] or row["content"][:400],
                    (
                        f"- record_id: `{row['record_id']}` | "
                        f"revision_id: `{row['revision_id']}` | "
                        f"class: {row['record_class']} | "
                        f"confidence: {row['confidence']:.2f}"
                    ),
                    "",
                ]
            )
        if not rows:
            lines.extend(["_No current records selected._", ""])
        return lines

    @staticmethod
    def _join(lines: list[str]) -> str:
        return "\n".join(lines).strip() + "\n"


class HermesProjection:
    """One-way DB -> Hermes file projection with an auditable manifest."""

    def __init__(
        self,
        store: MemoryStore,
        hermes_home: str | Path,
        *,
        memory_spec: SummarySpec | None = None,
        user_spec: SummarySpec | None = None,
    ):
        self.store = store
        self.hermes_home = Path(hermes_home)
        self.projector = SummaryProjector(store)
        self.memory_spec = memory_spec or SummarySpec(
            name="memory",
            title="Memory",
            exclude_domains=("user",),
        )
        self.user_spec = user_spec or SummarySpec(
            name="user",
            title="User",
            domains=("user",),
        )

    @property
    def memories_dir(self) -> Path:
        return self.hermes_home / "memories"

    def render(self) -> dict[str, str]:
        return {
            "MEMORY.md": self.projector.render(self.memory_spec),
            "USER.md": self.projector.render(self.user_spec),
        }

    def write(self) -> dict[str, Any]:
        self.store.initialize()
        rendered = self.render()
        self.memories_dir.mkdir(parents=True, exist_ok=True)
        hashes: dict[str, str] = {}
        for name, content in rendered.items():
            self._atomic_write(self.memories_dir / name, content)
            hashes[name] = hashlib.sha256(content.encode("utf-8")).hexdigest()
        manifest = {
            "schema": "agent-memory-hermes-projection/v1",
            "canonical_database": str(self.store.db_path.resolve()),
            "files": hashes,
        }
        self._atomic_write(
            self.memories_dir / ".agent-memory-core-projection.json",
            json.dumps(
                manifest,
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n",
        )
        return {
            **manifest,
            "hermes_home": str(self.hermes_home.resolve()),
            "projection_parity": self.verify(),
        }

    def verify(self) -> bool:
        expected = self.render()
        return all(
            (self.memories_dir / name).is_file()
            and (self.memories_dir / name).read_text(encoding="utf-8")
            == content
            for name, content in expected.items()
        )

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        fd, temporary = tempfile.mkstemp(
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
